// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Client.Data;

#nullable disable

namespace POS.Client.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20260623160804_AddProductNameToSaleItems")]
    partial class AddProductNameToSaleItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("POS.Client.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("POS.Client.Models.LocalInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("POS.Client.Models.LocalMaterial", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinStock")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("POS.Client.Models.LocalModifierGroup", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSelect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSelect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionType")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.ToTable("ModifierGroups");
                });

            modelBuilder.Entity("POS.Client.Models.LocalModifierOption", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalModifierGroupServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuantityConsumed")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.HasIndex("LocalModifierGroupServerId");

                    b.ToTable("ModifierOptions");
                });

            modelBuilder.Entity("POS.Client.Models.LocalPayment", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalSaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalSaleLocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("LocalSaleLocalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProduct", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDecimalQty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProductModifier", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalProductServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.HasIndex("LocalProductServerId");

                    b.ToTable("ProductModifiers");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProductVariant", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalProductServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.HasIndex("LocalProductServerId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSale", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PosClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaleNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSaleItem", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalSaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalSaleLocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("LocalSaleId");

                    b.HasIndex("LocalSaleLocalId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSaleItemModifier", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalSaleItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalSaleItemLocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("LocalSaleItemId");

                    b.HasIndex("LocalSaleItemLocalId");

                    b.ToTable("SaleItemModifiers");
                });

            modelBuilder.Entity("POS.Client.Models.LocalShift", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualCash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Difference")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedCash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PosClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StartingCash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncError")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("POS.Client.Models.LocalUser", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POS.Client.Models.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("POS.Client.Models.LocalModifierOption", b =>
                {
                    b.HasOne("POS.Client.Models.LocalModifierGroup", null)
                        .WithMany("Options")
                        .HasForeignKey("LocalModifierGroupServerId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalPayment", b =>
                {
                    b.HasOne("POS.Client.Models.LocalSale", null)
                        .WithMany()
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Client.Models.LocalSale", null)
                        .WithMany("Payments")
                        .HasForeignKey("LocalSaleLocalId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProductModifier", b =>
                {
                    b.HasOne("POS.Client.Models.LocalProduct", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("LocalProductServerId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProductVariant", b =>
                {
                    b.HasOne("POS.Client.Models.LocalProduct", null)
                        .WithMany("Variants")
                        .HasForeignKey("LocalProductServerId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSaleItem", b =>
                {
                    b.HasOne("POS.Client.Models.LocalSale", null)
                        .WithMany()
                        .HasForeignKey("LocalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Client.Models.LocalSale", null)
                        .WithMany("Items")
                        .HasForeignKey("LocalSaleLocalId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSaleItemModifier", b =>
                {
                    b.HasOne("POS.Client.Models.LocalSaleItem", null)
                        .WithMany()
                        .HasForeignKey("LocalSaleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Client.Models.LocalSaleItem", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("LocalSaleItemLocalId");
                });

            modelBuilder.Entity("POS.Client.Models.LocalModifierGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("POS.Client.Models.LocalProduct", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("POS.Client.Models.LocalSaleItem", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
